package prod.to_rework.smoke.client_level;

import com.carespeak.domain.entities.client.Client;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;
import prod.smoke.client_level.AbstractClientLevelTest;

//TODO: Implement this test to the end
public class ClientOptInKeywordsTest extends AbstractClientLevelTest {

    private String programName;
    private Client client;

    @BeforeClass
    public void prepareClientData() {
        programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        client = getTestClientByCode("OptIn client");
    }

    @Test(description = "Change opt-in keywords and see if they're working as expected")
    public void addedFooterAppearsOnWebForm() {
        site.clientSteps().setOptInKeyWords(client, "Go", "NotGo", "????", "sure");
        System.out.println();
    }
}
