package smoke;

import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class ClientOptInKeywordsTest extends SmokeBaseTest {

    @BeforeClass
    public void prepareClientData() {
        programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        client = createNewClient();
        site.loginSteps().openSite().loginAs(user, password);
    }

    @Test(description = "Change opt-in keywords and see if they're working as expected")
    public void addedFooterAppearsOnWebForm() {
        site.clientSteps().setOptInKeyWords(client, "Go", "NotGo", "????", "sure");
        System.out.println();
    }

    @AfterClass
    public void removeClient() {
        removeClient(client);
    }
}
