package smoke;

import com.carespeak.domain.entities.common.Day;
import com.carespeak.domain.entities.common.Sex;
import com.carespeak.domain.entities.message.MessageLogItem;
import com.carespeak.domain.entities.program.Patient;
import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class ConsentManagementTest extends SmokeBaseTest {

    private static final String FROM_PHONE_NUMBER = "+15554622669";
    private static final String TO_ENDPOINT = "twilioSmsSender5 [TWILIO +17542272273]";

    @BeforeClass
    public void prepareClientData() {
        programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        client = createNewClient();
        site.loginSteps().openSite().loginAs(user, password);
    }

    @Test(description = "Check if added header/footer appear on the web form and if made changes are visible")
    public void addedFooterAppearsOnWebForm() {
        site.clientSteps()
                .addOptOutHeader(client, "Auto added header")
                .addOptOutBody(client, "Auto added body")
                .addOptOutFooter(client, "Auto added footer");

        //TODO: implement testcase assertion
        System.out.println();
    }

    @AfterClass
    public void removeClient() {
        removeClient(client);
    }
}
