package smoke;

import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class ProgramTest extends SmokeBaseTest {

    private final String PROGRAM_NAME = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");

    @BeforeClass
    public void prepareProgram() {
        client = createNewClient();
        site.loginSteps().openSite().loginAs(user, password);
    }

    @Test(description = "Add new program")
    public void addNewProgram() {
        site.programSteps().addNewProgram(client.getName(), PROGRAM_NAME, ProgramAccess.PUBLIC);

        String actualProgramName = site.programSteps()
                .getProgramByName(client.getName(), PROGRAM_NAME);
        Assert.assertEquals(actualProgramName, PROGRAM_NAME, "Actual program differs from expected program");
    }

    @Test(description = "Check that program is set to public")
    public void publicProgram() {
        String actualAccess = site.programSteps()
                .getProgramAccessModifier(client.getName(), ProgramAccess.PUBLIC.getValue() + " (Visit here)");

        Assert.assertEquals(actualAccess, ProgramAccess.PUBLIC.getValue(), "Actual access differs from expected access");
    }

    @AfterClass
    public void removeClient() {
        removeClient(client);
    }
}
