package smoke;

import base.BaseTest;
import com.carespeak.domain.entities.message.Module;
import com.carespeak.domain.entities.program.Client;
import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;

public class SmokeBaseTest extends BaseTest {

    protected Client client;
    protected String programName;

    @BeforeClass
    public void prepareClient() {
        client = createClient();

        site.loginSteps()
                .openSite()
                .loginAs(user, password);

        Client actualClient = site.adminToolsSteps()
                .addNewClient(client, Module.CHECK_ALL)
                .getClientByCode(client.getCode());

        Assert.assertEquals(actualClient, client, "Actual client differs from expected client");
        programName = createProgram(client);
    }

    @AfterClass
    public void removeClient() {
        site.loginSteps()
                .openSite()
                .loginAs(user, password);
        site.adminToolsSteps()
                .removeClient(client);

        site.loginSteps()
                .openSite()
                .loginAs(user, password);
        Client shouldBeRemoved = site.adminToolsSteps()
                .getClientByCode(client.getCode());
        Assert.assertNull(shouldBeRemoved, "Client " + client + " was not removed!");
    }

    protected Client createClient() {
        Client client = new Client();
        client.setCode("AutoGenerated-" + getFormattedDate("dd-MM-yy-H-mm"));
        client.setName("Automator " + getRandomString());
        client.setEndpoint("twilioSmsSender5 [TWILIO +17542272273]");
        client.setModules(Module.getAllModules());
        return client;
    }

    protected String createProgram(Client client) {
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        site.programSteps().addNewProgram(client.getName(), programName, ProgramAccess.PUBLIC);
        //TODO: assert that program created
        return programName;
    }


}
