package smoke;

import base.BaseTest;
import com.carespeak.domain.entities.message.Module;
import com.carespeak.domain.entities.program.Client;
import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.Assert;

import java.util.concurrent.atomic.AtomicInteger;

public abstract class SmokeBaseTest extends BaseTest {

    protected Client client;
    protected String programName;

    private static AtomicInteger clientsCount = new AtomicInteger(0);

    protected void prepareClient() {
        client = createClient();

        site.loginSteps()
                .openSite()
                .loginAs(user, password);

        Client actualClient = site.adminToolsSteps()
                .addNewClient(client, Module.CHECK_ALL)
                .getClientByCode(client.getCode());

        Assert.assertEquals(actualClient, client, "Actual client differs from expected client");
    }

    protected void createProgram() {
        programName = createProgram(client);
    }

    protected Client createClient() {
        int number = clientsCount.addAndGet(1);
        Client client = new Client();
        client.setCode("AutoGenerated-" + number + "-" + getFormattedDate("dd-MM-yy-H-mm-ss"));
        client.setName("Automator " + getRandomString());
        client.setEndpoint("twilioSmsSender5 [TWILIO +17542272273]");
        client.setModules(Module.getAllModules());
        return client;
    }

    protected String createProgram(Client client) {
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        site.programSteps().addNewProgram(client.getName(), programName, ProgramAccess.PUBLIC);
        //TODO: assert that program created
        return programName;
    }

    protected void removeClient() {
        if (client != null) {
            site.loginSteps()
                    .openSite()
                    .loginAs(user, password);
            site.adminToolsSteps()
                    .removeClient(client);

            site.loginSteps()
                    .openSite()
                    .loginAs(user, password);
            Client shouldBeRemoved = site.adminToolsSteps()
                    .getClientByCode(client.getCode());
            Assert.assertNull(shouldBeRemoved, "Client " + client + " was not removed!");
        }
    }

}
