package smoke;

import com.carespeak.domain.entities.campaign.CampaignAccess;
import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

public class WebHooksTest extends SmokeBaseTest {

    private static final String FROM_PHONE_NUMBER = "+15554622669";
    private static final String TO_ENDPOINT = "twilioSmsSender5 [TWILIO +17542272273]";

    @BeforeClass
    public void prepareClientData() {
        programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        client = createNewClient();
        site.loginSteps().openSite().loginAs(user, password);
    }

    @Test(description = "Add a link and webhook name, try adding it to an SMS message to check if the shortened link that goes out leads to a needed link")
    public void addedFooterAppearsOnWebForm() {
        site.clientSteps()
                .addWebhook(client, "webhook_test", "http://webhooktest.com", null);
        site.campaignSteps()
                .addCampaign(client, "AutoTestCampaign", CampaignAccess.PUBLIC, "Automation created campaign", null);
        //TODO: implement testcase assertion
        System.out.println();
    }

    @AfterClass
    public void removeClient() {
        removeClient(client);
    }
}
