package prod.smoke.program_level;

import com.carespeak.domain.entities.client.Client;
import com.carespeak.domain.entities.program.Patient;
import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.List;

public class ProgramManagementTest extends AbstractProgramLevelTest {

    private Client client;
    private String programName;
    private String clientName;
    private Patient patient;
    private String patientName;

    @BeforeClass
    public void prepareClientData() {
        client = getTestClientByCode("ProgramLevelTest client " + getFormattedDate("dd-MM-yy-H-mm"));
        clientName = client.getName();
        programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        programName = getTestProgramByName(programName, client);
        patient = new Patient();
        patient.setFirstName("ProgramManagementTestPatient " + getFormattedDate("dd-MM-yy-H-mm"));
        patient.setCellPhone(getGeneratedPhoneNumber());
        patient.setTimezone("Eastern Time (New York)");
        patient.setEmail("testpatient@optimizerx.com");
    }

    @Test(description = "Add new program")
    public void addNewProgram_MHM_T25() {
        String actualProgramName = site.programSteps()
                .getProgramByName(clientName, programName);
        Assert.assertEquals(actualProgramName, programName, "Actual program differs from expected program");
    }

    @Test(description = "Check that program is set to public", dependsOnMethods = "addNewProgram_MHM_T25")
    public void publicProgram_MHM_T168() {
        String actualAccess = site.programSteps()
                .getProgramAccessModifier(clientName, ProgramAccess.PUBLIC.getValue() + " (Visit here)");

        Assert.assertEquals(actualAccess, ProgramAccess.PUBLIC.getValue(), "Actual access differs from expected access");
    }

    @Test(description = "Add new patient manually")
    public void addPatientManually_MHM_T114(){
        site.programSteps().addNewPatientAllFields(patient, client, programName);

        String actualPatientName = site.programSteps()
                .getPatientByName(clientName, programName, patient.getFirstName());

        Assert.assertEquals(actualPatientName, patient.getFirstName(), "Actual patient differs from expected patient");
    }

    @AfterClass(alwaysRun=true)
    public void removeProgram() {
//        site.programSteps().removeProgram(client, programName);
//        List<String> programs = site.programSteps().getProgramsForClient(client);
//        Assert.assertFalse(programs.contains(programName), "Program '" + programName + "' was not removed!");
        site.adminToolsSteps().removeClient(client);
    }
}
