package prod.smoke.program_level;

import com.carespeak.domain.entities.client.Client;
import com.carespeak.domain.entities.program.Patient;
import com.carespeak.domain.entities.program.ProgramAccess;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.List;

public class ProgramManagementTest extends AbstractProgramLevelTest {

    private Client client;
    private String clientName;
    private Patient patient;

    @BeforeClass
    public void prepareClientData() {
        client = getTestClientByCode("ProgramLevelTest client " + getFormattedDate("dd-MM-yy-H-mm"));
        clientName = client.getName();
        patient = new Patient();
        patient.setFirstName("ProgramManagementTestPatient " + getFormattedDate("dd-MM-yy-H-mm"));
        patient.setCellPhone(getGeneratedPhoneNumber());
        patient.setTimezone("Eastern Time (New York)");
        patient.setEmail("testpatient@optimizerx.com");
    }

    @Test(description = "Add new program")
    public void addNewProgram_MHM_T25() {
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");

        site.programSteps().addNewProgram(clientName, programName, ProgramAccess.PUBLIC);

        String actualProgramName = site.programSteps()
                .getProgramByName(clientName, programName);
        Assert.assertEquals(actualProgramName, programName, "Actual program differs from expected program");
    }

    @Test(description = "Check that program is set to public")
    public void publicProgram_MHM_T168() {
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");

        site.programSteps().addNewProgram(clientName, programName, ProgramAccess.PUBLIC);

        String actualAccess = site.programSteps()
                .getProgramAccessModifier(clientName, ProgramAccess.PUBLIC.getValue() + " (Visit here)");

        Assert.assertEquals(actualAccess, ProgramAccess.PUBLIC.getValue(), "Actual access differs from expected access");
    }

    @Test(description = "Add new patient manually")
    public void addPatientManually_MHM_T114(){
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        patient.setCellPhone(getGeneratedPhoneNumber()); //required to have unique patient for this test, in case it runs in 2nd time as a flaky test
        patient.setFirstName("ProgramManagementTestPatient-" + getRandomString());

        site.programSteps().addNewProgram(clientName, programName, ProgramAccess.PUBLIC);
        site.programSteps().addNewPatientAllFields(patient, client, programName);

        String actualPatientName = site.programSteps()
                .getPatientByName(clientName, programName, patient.getFirstName());

        Assert.assertEquals(actualPatientName, patient.getFirstName(), "Actual patient differs from expected patient");
    }

    @Test(description = "Delete patient from program")
    public void deletePatientFromProgram_MHM_T143(){
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");
        patient.setCellPhone(getGeneratedPhoneNumber()); //required to have unique patient for this test, in case it runs in 2nd time as a flaky test
        patient.setFirstName("ProgramManagementTestPatient-" + getRandomString());

        site.programSteps().addNewProgram(clientName, programName, ProgramAccess.PUBLIC);
        site.programSteps().addNewPatientAllFields(patient, client, programName);

        String actualPatientName = site.programSteps()
                .getPatientByName(clientName, programName, patient.getFirstName());

        Assert.assertEquals(actualPatientName, patient.getFirstName(), "Actual patient differs from expected patient");
    }

    @AfterClass(alwaysRun = true)
    public void removeClient() {
        site.adminToolsSteps()
                .removeClient(client);
    }
}
