package prod.smoke.program_level;

import com.carespeak.domain.entities.client.Client;
import com.carespeak.domain.entities.program.ProgramAccess;
import com.carespeak.domain.entities.program.ProgramOptOutForm;
import org.testng.Assert;
import org.testng.annotations.AfterClass;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.Test;

import java.util.List;

public class ProgramConsentManagementTest extends AbstractProgramLevelTest {

    private Client client;

    @BeforeClass
    public void prepareClientData() {
        client = getTestClientByCode("ProgramLevelTestConsent Client " + getFormattedDate("dd-MM-yy-H-mm"));
    }

    @Test(description = "Check if added header/footer appear on the web form and if made changes are visible")
    public void addedFooterAppearsOnWebForm_MHM_T174() {
        ProgramOptOutForm expectedOptOutForm = new ProgramOptOutForm("Auto added header", "Auto added body", "Auto added footer");
        String programName = "AutoGenerated program " + getFormattedDate("dd-MM-yy-H-mm");

        site.clientSteps()
                .addOptOutHeader(client, expectedOptOutForm.getHeader())
                .addOptOutBody(client, expectedOptOutForm.getBody())
                .addOptOutFooter(client, expectedOptOutForm.getFooter());

        ProgramOptOutForm actualOptOutForm = site.programSteps()
                .addNewProgram(client.getName(), programName, ProgramAccess.PUBLIC)
                .addOptOutHeader(client, programName, null)
                .getProgramOptOutForm(client.getName(), programName);

        Assert.assertEquals(actualOptOutForm, expectedOptOutForm, "OptOutForm not appear on program level");
    }

    @AfterClass(alwaysRun = true)
    public void removeClient() {
        site.adminToolsSteps()
                .removeClient(client);
    }
}
